### ISSUE TITLE
Npm package not found.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reason-react-native/paper#2]
https://www.npmjs.com/@reason-react-native/paper is not available.

**Comment by kncs** [comment]
Still not available, is anybody still maintaining this repo ?

**Comment by MoOx** [comment]
`yarn add https://github.com/reason-react-native/paper` should help until this lands on npm.

**Comment by enieber** [comment]
Add this in README

**Comment by MoOx** [comment]
Now it is!
